### ISSUE TITLE
Make This Repo Open

### ISSUE THREAD

**Issue by yuya-takeyama** [quipper/circleci-env#26]
## TODO

* Make repos public
  * [x] https://github.com/quipper/circleci-env-test-01
  * [x] https://github.com/quipper/circleci-env-test-02
  * [x] https://github.com/quipper/circleci-env
* Check if secret info exists
  * [x] https://github.com/quipper/circleci-env-test-01
  * [x] https://github.com/quipper/circleci-env-test-02
  * [x] https://github.com/quipper/circleci-env

**Comment by suzuki-shunsuke** [comment]
@yuya-takeyama 
This repository is already public, so we can close this issue.

**Comment by yuya-takeyama** [comment]
@suzuki-shunsuke 
`circleci-env-test-01` and `circleci-env-test-02` are not yet public.

**Comment by suzuki-shunsuke** [comment]
Oh, sorry. I misunderstood. 🙇‍♂️

**Comment by yuya-takeyama** [comment]
I've made them public.
Let's close now.
